language: java
jdk:
  - oraclejdk8
  
language: node_js
node_js:
  - "6.9"

branches:
  only:
    - CI

before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install
- ng build
  
  script: 
  - mvn clean package
