language: java  

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g @angular/cli
  - npm install -g karma
  - npm install

script: "mvn clean package -X"

deploy:
  - provider: s3
    ⋮ # rest of S3 deployment for MyApp.zip
  - provider: codedeploy
    access_key_id: "AKIAIFOSIN55MDVMPREA"
    secret_access_key: "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"
    bucket: "aws-sms-bucket"
    key: latest/sms.war
    application: SMS
    deployment_group: MyDeploymentGroup
